# Generated by Django 3.2.16 on 2023-01-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_city_set', to='cities.city'),
        ),
    ]
