# Generated by Django 3.2.16 on 2023-01-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_bustest_from_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusTest',
        ),
    ]
